# Initialize Starship prompt
eval "$(starship init zsh)"

# Load ZSH plugins
if [ -d "$HOME/.config/zsh/plugins" ]; then
  for plugin in "$HOME/.config/zsh/plugins"/*.zsh; do
    [ -f "$plugin" ] && source "$plugin"
  done
fi

# Homebrew configuration
eval "$(/opt/homebrew/bin/brew shellenv)"

# Ruby configuration
export LDFLAGS="-L$(brew --prefix libyaml)/lib"
export CPPFLAGS="-I$(brew --prefix libyaml)/include"
export RUBY_YJIT_ENABLE=1
export RUBY_CONFIGURE_OPTS=--enable-yjit

# Development environment setup
# Initialize mise (previously rtx) for version management
eval "$(mise activate zsh)"

eval "$(fzf --zsh)"

# PostgreSQL path configuration
export PATH="/opt/homebrew/opt/postgresql@17/bin:$PATH"

export PGGSSENCMODE="disable"

export PATH="$HOME/.local/bin:$PATH"
